// <auto-generated />
namespace Delicious.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "7.1.60.0")]
    public sealed partial class addAdmin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addAdmin));
        
        string IMigrationMetadata.Id
        {
            get { return "202205291256106_addAdmin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
